### PR TITLE
Steps for Xampp windows

### PR DESCRIPTION
**Pull request by gptshubham595**
This will save many people time

### CODE REVIEW

**Review by gptshubham595 — COMMENTED** [review]
Missed one line

**Review by gptshubham595 — COMMENTED** [review]
Added Create database and table

**Review by gptshubham595 — COMMENTED** [review]
Steps for both XAMPP AND WEBHOST

**Review by gptshubham595 — COMMENTED** [review]
modified urls

**Review by akrajilwar — APPROVED** [review]

**Pull request merged**
